# Generated by Django 4.1.4 on 2022-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Файл изображения'),
        ),
    ]
